package com.gmpire.guruklub.util.appEvents

object AppEventKEY {
    const val LIMITED_HEARTS_PURCHASE = "LIMITED_HEARTS_PURCHASE"
    const val UNLIMITED_HEARTS_PURCHASE = "UNLIMITED_HEARTS_PURCHASE"
    const val LIVE_EXAM_PARTICIPANTS = "LIVE_EXAM_PARTICIPANTS"
    const val ADS_FREE_PACKAGE_BUYER = "ADS_FREE_PACKAGE_BUYER"
    const val CHALLENGE_TAKER = "CHALLENGE_TAKER"
    const val MODEL_TEST_START = "MODEL_TEST_START"


}